name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build without tests
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        env:
          RDSENDPOINT: ${{ secrets.RDSENDPOINT }}
          RDSNAME: ${{ secrets.RDSNAME }}
          RDSPASSWORD: ${{ secrets.RDSPASSWORD }}
          SECRETKEY: ${{ secrets.SECRETKEY }}

      - name: Copy jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/app"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            pkill -f "java -jar" || true
            nohup java -jar /home/ubuntu/app/$JAR_FILE > /home/ubuntu/app/log.txt 2>&1 &